version: "3.8"

services:
  flask:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - jenkins
    healthcheck:
      test: ["CMD" , "curl", "-f" , "http://localhost:5000" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - flask
  
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins_server
    ports:
      - "8000:8000"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Allows Jenkins to manage Docker

volumes:
  jenkins_home:
    driver: local