
---
  - name: "Play book to Install Falask App Via Ansible "
    hosts: ec2
    become: yes
    tasks:
      - name: Update all packages
        yum:
          name: '*'
          state: latest
      
      - name: Install required dependencies
        yum:
          name:
            - git
            # - curl
            - python3
            # - amazon-linux-extras
          state: present

      # - name: Enable Docker in Amazon Linux
      #   shell: amazon-linux-extras enable docker
      #   when: ansible_distribution == "Amazon" and ansible_distribution_version.startswith("2")

      # - name: Install Docker Amazon Linux 2
      #   yum:
      #     name: docker
      #     state: present
      #   when: ansible_distribution == "Amazon" and ansible_distribution_version.startswith("2") 

      - name: Install Docker Amazon Linux 2023
        dnf:
          name: docker
          state: present
        when: ansible_distribution == "Amazon" and ansible_distribution_version.startswith("2023") 
      
      - name: Start and Enable Docker
        service: 
          name: docker
          state: started
          enabled: yes

      - name: Wait for Docker daemon to be ready
        shell: |
          while (! docker info > /dev/null 2>&1); do sleep 1; done
        retries: 10
        delay: 5
        register: docker_ready
        until: docker_ready.rc == 0

      - name: Add 'ec2-user' to Docker group
        user:
          name: ec2-user
          groups: docker
          append: yes
      
      - name: Install Docker Compose
        get_url:
            url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64"
            dest: "/usr/local/bin/docker-compose"
            mode: "0755"

      - name: Verify Docker Compose Installation
        shell: docker-compose --version
        register: docker_compose_version

      - name: Display Docker Compose Version
        debug:
          msg: "Display Docker version {{ docker_compose_version.stdout }}"

      - name: Clone the project from repo
        git:
          repo: "https://github.com/Icode4passion/flaskAnsibeProj.git"
          dest: /home/ec2-user/flask-app

      - name: Change permission of project directory
        file: 
          path: /home/ec2-user/flask-app
          owner: ec2-user
          group: ec2-user 
          mode: "0755"
      - name: Create Jenkins home directory with correct permissions
        file:
          path: /home/ec2-user/flask-app/jenkins_home
          state: directory
          owner: 1000
          group: 1000
          mode: "0755"

      - name: Deploy all containers using Docker Compose
        become: yes
        become_user: ec2-user
        shell: |
          cd /home/ec2-user/flask-app
          /usr/local/bin/docker-compose up                   
        args: 
          executable: /bin/bash
        register: compose_run
        ignore_errors: yes
        # async: 600         # run for max 5 minutes
        # poll: 30
      # - name: Show DockerCompose output
      #   debug:
      #     var: compose_run.stdout_lines

      # - name: Show running containers
      #   shell: docker ps -a
      #   register: docker_ps
      #   ignore_errors: yes

      # - debug:
      #     var: docker_ps.stdout_lines

      # # ⬇️ Add this right after the docker-compose up task
      # - name: Get docker-compose logs
      #   shell: |
      #     cd /home/ec2-user/flask-app
      #     /usr/local/bin/docker-compose logs
      #   register: compose_logs
      #   ignore_errors: yes

      # - debug:
      #     var: compose_logs.stdout_lines

      - name: wait for Jenkins to start
        wait_for:
          port: 8000
          timeout: 60
        
      - name: Print initial Jenkins admin password
        shell: cat /var/jenkins_home/secrets/initialAdminPassword
        register: jenkins_password

      - name: Show Jenkins Password
        debug:
          msg: "Jenkins initial password {{ jenkins_password.stdout }}"






